# Generated by Django 2.2.4 on 2019-09-08 23:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('profile_description', models.TextField()),
                ('establishment_date', models.DateField(default=datetime.datetime.now)),
                ('company_website_url', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_location', models.CharField(blank=True, max_length=150)),
                ('company_tagline', models.CharField(blank=True, max_length=250)),
                ('company_linkedin', models.CharField(blank=True, max_length=200)),
                ('company_email', models.CharField(blank=True, max_length=100)),
                ('company_phone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15)),
                ('contact_number', models.CharField(max_length=10)),
                ('registration_date', models.DateField(default=datetime.datetime.now)),
                ('user_address', models.CharField(blank=True, max_length=200)),
                ('profile_picture', models.ImageField(upload_to='Profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seeker_resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_path', models.FileField(upload_to='userResume/')),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('degree', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user_account')),
            ],
        ),
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15)),
                ('contact_number', models.CharField(max_length=10)),
                ('registration_date', models.DateField(default=datetime.datetime.now)),
                ('user_address', models.CharField(blank=True, max_length=200)),
                ('recruiter_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('job_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published')),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=50)),
                ('job_experience', models.IntegerField()),
                ('job_education', models.CharField(max_length=20)),
                ('job_type', models.CharField(default='Full time', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('job_skills', models.TextField(blank=True)),
                ('job_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('status', models.TextField(default='pending')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_account')),
            ],
        ),
    ]
